name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        id: snake-gif
        with:
          github_token: ${{ secrets.TOKEN }}
          output: dist/github-snake.svg

      - name: Commit Files
        run: |
          git config --local user.email "howardjohn855@gmail.com"
          git config --local user.name "NFT Knight"
          git add dist/github-snake.svg
          git commit -m "Generated snake"
          git push
